# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingFloors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('interfloor', models.IntegerField(default=3)),
                ('population', models.IntegerField(default=50)),
                ('entry', models.IntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.Building')),
            ],
        ),
    ]
