# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_buildingfloors'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingfloors',
            name='local_id',
            field=models.IntegerField(default=0),
        ),
    ]
