# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_auto_20170519_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengersArrivalTime', models.IntegerField(default=3600)),
                ('arrivalRate', models.FloatField(default=12)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.Building')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationRunDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.SimulationDetails')),
            ],
        ),
    ]
