# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_simulationdetails_simulationrundetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='floor_dist',
            field=models.FloatField(default=3),
        ),
    ]
