# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_auto_20170519_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRunDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField()),
                ('departure', models.FloatField()),
                ('INT', models.FloatField()),
                ('load', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField()),
                ('AINT', models.FloatField()),
                ('ACLF', models.FloatField()),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.SimulationDetails')),
            ],
        ),
        migrations.CreateModel(
            name='StatPassengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField()),
                ('destFloor', models.IntegerField()),
                ('arrTime', models.FloatField()),
                ('depTime', models.FloatField()),
                ('destTime', models.FloatField()),
                ('WT', models.FloatField()),
                ('TTD', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StatSimulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.SimulationDetails')),
            ],
        ),
        migrations.AddField(
            model_name='carrundetails',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.StatCars'),
        ),
        migrations.AddField(
            model_name='carrundetails',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.SimulationDetails'),
        ),
    ]
