# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0008_auto_20170519_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='statpassengers',
            name='simulation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simulator.SimulationDetails'),
            preserve_default=False,
        ),
    ]
