# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0009_statpassengers_simulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrundetails',
            name='car',
            field=models.IntegerField(),
        ),
    ]
