# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0011_statsimulation_aavg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsimulation',
            name='aavg',
        ),
    ]
