# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0012_remove_statsimulation_aavg'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsimulation',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
