# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0013_statsimulation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
