# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0015_simulationdetails_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsimulation',
            name='date',
        ),
        migrations.AddField(
            model_name='statsimulation',
            name='ACLF',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='statsimulation',
            name='AINT',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='statsimulation',
            name='ATTD',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='statsimulation',
            name='AWT',
            field=models.FloatField(default=0),
        ),
    ]
