# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0017_auto_20170524_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.FloatField(default=0)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.SimulationDetails')),
            ],
        ),
        migrations.AddField(
            model_name='carrundetails',
            name='step',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='statpassengers',
            name='step',
            field=models.FloatField(default=0),
        ),
    ]
