# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('simulator', '0020_statcars_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardUsers',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            bases=('auth.group',),
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'permissions': (('view_building', 'Can see available buildings'),)},
        ),
    ]
