# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0022_auto_20170606_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='type',
        ),
        migrations.AlterField(
            model_name='requirements',
            name='building_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.BuildingTypes'),
        ),
    ]
