# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0024_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='AR',
            field=models.FloatField(default=5),
        ),
    ]
