# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0025_requirements_ar'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatSimulationSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(default=0, max_length=200)),
                ('AR', models.FloatField(default=0)),
                ('AWT', models.FloatField(default=0)),
                ('AINT', models.FloatField(default=0)),
                ('ATTD', models.FloatField(default=0)),
                ('ACLF', models.FloatField(default=0)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.SimulationDetails')),
            ],
        ),
        migrations.AlterField(
            model_name='requirements',
            name='AR',
            field=models.FloatField(),
        ),
    ]
