# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0026_auto_20170606_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingtypes',
            old_name='type',
            new_name='name',
        ),
    ]
