# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0027_auto_20170606_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='type',
        ),
        migrations.AddField(
            model_name='building',
            name='b_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simulator.BuildingTypes'),
            preserve_default=False,
        ),
    ]
