# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0031_auto_20170609_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
