# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0034_auto_20170609_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='statpassengers',
            name='entryFloor',
            field=models.IntegerField(default=0),
        ),
    ]
