# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0038_simulationrundetails_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrundetails',
            name='local_id',
            field=models.FloatField(default=0),
        ),
    ]
