# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0039_simulationrundetails_local_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMotionCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.FloatField(default=0)),
                ('car', models.IntegerField()),
                ('time', models.FloatField()),
                ('height', models.FloatField()),
                ('speed', models.FloatField()),
                ('acc', models.FloatField()),
                ('jerk', models.FloatField()),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.SimulationDetails')),
            ],
        ),
    ]
