# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0040_carmotioncycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmotioncycle',
            name='acc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='carmotioncycle',
            name='car',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carmotioncycle',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='carmotioncycle',
            name='jerk',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='carmotioncycle',
            name='speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='carmotioncycle',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
