# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0044_auto_20170720_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmotioncycle',
            old_name='simulation',
            new_name='simulation_id',
        ),
    ]
