# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0045_auto_20170720_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmotioncycle',
            old_name='simulation_id',
            new_name='simulation_id_f',
        ),
        migrations.AddField(
            model_name='carmotioncycle',
            name='simulation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='simulator.SimulationDetails'),
        ),
    ]
