# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0048_remove_carmotioncycle_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmotioncycle',
            name='simulation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='simulator.SimulationDetails'),
        ),
        migrations.AddField(
            model_name='carmotioncycle',
            name='simulation_id_f',
            field=models.FloatField(default=0),
        ),
    ]
