# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0049_auto_20170720_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmotioncycle',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.SimulationDetails'),
        ),
    ]
