# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0051_remove_carmotioncycle_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmotioncycle',
            name='building_id_f',
            field=models.FloatField(default=0),
        ),
    ]
